pipeline:
  name: harness-trigger-pipeline-logs
  identifier: harnesstriggerpipelinelogs
  projectIdentifier: Platform_Engineering
  orgIdentifier: SE_Sandbox
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.diegogithubapp
        repoName: harness-trigger-pipeline-logs
        build: <+input>
  stages:
    - stage:
        name: plugin image builder
        identifier: plugin_image_builder
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry
                  identifier: BuildAndPushDockerRegistry
                  spec:
                    connectorRef: account.DockerHubDiego
                    repo: diegokoala/harness-trigger-pipeline-logs
                    tags:
                      - <+codebase.shortCommitSha>
                    caching: true
    - stage:
        name: trigger pipeline e2e
        identifier: trigger_pipeline_e2e
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Plugin
                  name: Trigger Pipeline
                  identifier: Trigger_Pipeline
                  spec:
                    connectorRef: account.DockerHubDiego
                    image: diegokoala/harness-trigger-pipeline-logs
                    settings:
                      API_KEY: <+secrets.getValue("diego_pat")>
                      ACCOUNT_IDENTIFIER: 6_vVHzo9Qeu9fXvj-AcbCQ
                      ORG_IDENTIFIER: SE_Sandbox
                      PROJECT_IDENTIFIER: Platform_Engineering
                      PIPELINE_IDENTIFIER: financebackenddeploy
                      PIPELINE_YAML: "pipeline:\\n  identifier: financebackenddeploy\\n  properties:\\n    ci:\\n      codebase:\\n        build:\\n          spec:\\n            branch: main\\n          type: branch"
